---
title: "Final"
author: "Adam Guerra, Luke Todd, Riley Zamora"
date: "2023-06-11"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 4
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading Packages
library(tidyverse)
library(here)
library(janitor)
library(ggeffects)
library(performance)
library(naniar) 
library(flextable) 
library(car)
library(broom)
library(corrplot)
library(AICcmodavg)
library(GGally)
```


## Problem 1

#### Introduction


#### Methods
```{r}
# loading data
kang_seed <- read.table(here("data/sev208_kratseedbank_20120213.txt"), sep=',')
```


#### Results



## Problem 2

#### Introduction


#### Methods
```{r}
# loading data
shrub_com <- read.csv(here("data/shrubstudy_community_flower_counts.csv"))
shrub_ind <- read.csv(here("data/shrubstudy_individual_flower_counts.csv"))
shrub_seed <-read.csv(here("data/shrubstudy_seed.csv"))
shrub_pol <- read.csv(here("data/shrubstudy_pollinator.csv"))
```



#### Results






```{r}

```





























